### Matrizes e vetores com numpy
O Numpy tem um tipo especial para matrizes, que são listas de números.

In [1]:
import numpy as np

A = np.matrix("1.2 3 4;2.5 6 7")
print(A)

[[ 1.2  3.   4. ]
 [ 2.5  6.   7. ]]


In [2]:
print("Numero de linhas=" , np.shape(A)[0])
print("Número de Colunas =", np.shape(A)[1])

Numero de linhas= 2
Número de Colunas = 3


In [3]:
print(A[:,1]) # coluna 1 (a segunda coluna!)

[[ 3.]
 [ 6.]]


In [4]:
B=np.matrix(' 1 2 ;3 4')
B

matrix([[1, 2],
        [3, 4]])

In [5]:
B*A

matrix([[  6.2,  15. ,  18. ],
        [ 13.6,  33. ,  40. ]])

In [6]:
x=np.matrix('2;1;3')
x
print(A*x)

[[ 17.4]
 [ 32. ]]
