## tabela de Fourier
Fazemos uma partição do intervalo $[0,2\pi]$ em $N$ partes iguais começando com $x_0=0,$ depois $x_k = \frac{2k\pi}{N}$ até $x_{N-1}$. Para um número natural $L$ consideramos a família de funções $$\{ 1, \cos{x}, \sin{x}, \cos{2x}, \sin{2x}, \cdots, \cos{(L-1)x},\sin{(L-1)x}\}.$$ A função **tabelaFourier** deve produzir a tabela
$$\begin{array}{cccc}
x_0 & x_1& \cdots & x_{N-1} \\ 
1 & 1 & \cdots & 1 \\
\cos{x_0} & \cos{x_1} &\cdots & \cos{x_{N-1}}\\
\vdots    & \vdots   &    &\vdots \\
\sin{(L-1)x_0}&\sin{(L-1)x_1}& \cdots & \sin{(L-1)x_{N-1}}
\end{array}$$

In [6]:
import numpy as np
def tabelaFourier(N,L):
    x=np.array([2*k*np.pi/N for k in range(N)])
    tabela = [x]
    for u in range(L):
        tabela.append(np.array(np.cos(u*x)))
        if not(u == 0):
            tabela.append(np.array(np.sin(u*x)))
    return np.array(tabela)

In [7]:
A=tabelaFourier(3,2)

print(A)


[[ 0.         2.0943951  4.1887902]
 [ 1.         1.         1.       ]
 [ 1.        -0.5       -0.5      ]
 [ 0.         0.8660254 -0.8660254]]


In [8]:
B = tabelaFourier(4,3)
print(B)

[[  0.00000000e+00   1.57079633e+00   3.14159265e+00   4.71238898e+00]
 [  1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00]
 [  1.00000000e+00   6.12323400e-17  -1.00000000e+00  -1.83697020e-16]
 [  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00]
 [  1.00000000e+00  -1.00000000e+00   1.00000000e+00  -1.00000000e+00]
 [  0.00000000e+00   1.22464680e-16  -2.44929360e-16   3.67394040e-16]]


In [9]:
B[2,:]

array([  1.00000000e+00,   6.12323400e-17,  -1.00000000e+00,
        -1.83697020e-16])

In [11]:
np.dot(B[2,:],B[3,:])

1.2246467991473532e-16